### ISSUE TITLE
Query regarding new features

### ISSUE THREAD

**Issue by bholagabbar** [heroku/salesforce-bulk#46]
Hey @lambacck I'm the author of https://github.com/wingify/salesforce-bulkipy . We created this library primary because of:

* Added support for Two-Factor Authentication by routing authentication via simple-salesforce
* Added support for Salesforce Sandbox
* Added support for parsing unicode characters in CSV
* Explicit Upsert Support
* Fixed various other bugs
* Python 3 support

Has salesforce-bulk added integrated all of these features? If yes then then my fork library can be deemed redundant and I would like to add a link to the library README which redirects back to yours :)

**Comment by lambacck** [comment]
Version 2.0 will be API incompatible with the previous version. It includes support for Python 3, JSON and XML, a test suite that runs in Travis and performs integration tests and SimpleSalesforce as the password authentication mechanism. All outstanding code related bugs against this repo (and probably several more) have been fixed in the process (more documentation work is still required).

I'm not sure what that says in comparison to what's been done in your fork.

**Comment by lambacck** [comment]
I think all of the above (and more) are covered.
